[package]
name = "ee2-win-clipboard"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
windows-sys = { version = "0.61.2", features = [
  "Win32_Foundation",
  "Win32_System_DataExchange",
  "Win32_System_Memory",
  "Win32_UI_WindowsAndMessaging",
] }

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
strip = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
